### ISSUE TITLE
Grammar issues in application.xml file

### ISSUE THREAD

**Issue by amasino** [commoncriteria/application#163]
Hi,

I'm consuming this repository to have an xml version of all NIAP protection profiles, PP modules and Extended Packages. I've noticed that the grammar varies between one project and the other. 

Specifically, for this Protection Profile, I've noticed the following:
- Assurance activities are delimited by the <aactivity> tag, and each section (TSS, Guidance, Tests) does exist, but the tags appear only as delimiters, they do not include the text within the tags. For instance, instead of:

<TSS>This is the assurance activity that goes in the TSS</TSS>

All assurance activities appear as orphans and the tag is only used as delimiter:

<TSS/>This is the assurance activity.

This causes issues in the processing of the XML file with XSLT, which is  tag oriented. 

- Also, the file usualy includes <h:br/> tags to cause the text to break lines. I suggest enclosing text in separate paragraphs (h:p) so processing is easier.

Thanks,
Alejandro Masino

**Comment by jmcdaniels** [comment]
We will take this comment under consideration during the next planned update.  Thank you for the feedback.

**Comment by jfisherbah** [comment]
With respect to the tags, unclear what the status of the PP was when this comment was originally made but I believe it has been resolved. The text for the EAs exists in their own separate tags which include the actual data element within the tag (at least that is my assumption based on how the evaluation activity is populated now with separate TSS/Guidance/Test tags which I believe EAs didn't have previously). 

Please confirm whether the intent of the first part of the comment was met by how the <aactivity> tags are populated now.

With respect to the second point, <h:p> is the preferred usage although there are some cases where this conflicts with the schema and doesn't add the proper spacing between paragraphs. Historically <h:p/> was used to create a blank paragraph which produced the desired spacing with no limitations, but it is our understanding that this is not best practice because how that gets rendered is not standardized across different browsers. The PP has been migrated to <h:p> tags in replacement to both line breaks and blank paragraphs within prose, and will be reviewed for areas where this doesn't result in sufficient whitespace being added.

<h:br> tags still used when no padding is preferred (e.g., when there are multiple dependencies listed in an extended component definition).

Note as part of making this update, a reference error in the start of section 5.2 was observed and corrected (reference to security objectives for the TOE pointed to section 5.1 rather than to 4.1).

**Comment by jmcdaniels** [comment]
@amasino please confirm the above resolves this issue.

**Comment by jmcdaniels** [comment]
Closing issue due to lack of response.
